name: ugd_ui_widget
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  camera: ^0.10.5+5
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.2
  intl: ^0.17.0
  mobile_scanner: ^3.5.2
  path: ^1.8.3
  path_provider: ^2.1.1
  pdf: ^3.6.4
  printing: ^5.9.0
  qr_flutter: ^4.1.0
  screen_brightness: ^0.2.2+1
  shake: ^2.2.0
  shared_preferences: ^2.0.8
  cupertino_icons: ^1.0.2
  sqflite: ^2.2.6
  url_launcher: ^6.2.1

  barcode_widget: ^2.0.4

  uuid: ^3.0.6
  responsive_sizer: ^3.2.0


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
