name: ugd_ui_widget
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  barcode_widget: ^2.0.4
  camera: ^0.10.5+5
  drop_shadow: ^0.1.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.7
  fluttertoast: ^8.2.2
  google_fonts: ^6.1.0
  http: ^1.1.0
  image_picker: ^0.8.4
  intl: ^0.17.0
  mobile_scanner: ^3.5.2
  path: ^1.8.3
  path_provider: ^2.1.1
  pdf: ^3.6.4
  printing: ^5.9.0
  qr_flutter: ^4.1.0
  responsive_sizer: ^3.2.0
  screen_brightness: ^0.2.2+1
  shake: ^2.2.0
  shared_preferences: ^2.0.8
  sqflite: ^2.2.6
  url_launcher: ^6.2.1
  uuid: ^4.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
