name: ugd_ui_widget
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.2
  intl: ^0.17.0
  shared_preferences: ^2.0.8

  sqflite: ^2.2.6

  flutter_slidable: ^0.6.0

  path_provider: ^2.0.1

  qr_flutter: ^4.0.0

  screen_brightness: ^0.2.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - images/
