name: ugd_ui_widget
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  camera: ^0.10.5+5
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.2
  intl: ^0.17.0
  mobile_scanner: ^3.5.2
  path: ^1.8.3
  path_provider: ^2.1.1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.0.8
  sqflite: ^2.2.6
  shake: ^2.2.0
  url_launcher: ^6.2.1
  image_picker: ^0.8.4

  screen_brightness: ^0.2.2+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
